"""MANDATORY SAFETY DISCLAIMER (Implementation Directive #2).

Every AuraMed output — API response, chatbot message, TTS script, generated
leaflet or prescription draft — MUST carry this disclaimer. The FastAPI app
enforces it twice:

1. ``AuraMedResponse`` (common schemas) always serializes a ``disclaimer``
   field;
2. an HTTP middleware injects the ``X-AuraMed-Disclaimer`` response header.
"""
from __future__ import annotations

DISCLAIMER_EN = (
    "AuraMed AI output is for decision-support only; requires licensed "
    "physician review before clinical action."
)

DISCLAIMER_BN = (
    "AuraMed AI-এর আউটপুট শুধুমাত্র সিদ্ধান্ত-সহায়তার জন্য; চিকিৎসা সংক্রান্ত "
    "কোনো ব্যবস্থা নেওয়ার আগে অবশ্যই নিবন্ধিত চিকিৎসকের পর্যালোচনা প্রয়োজন।"
)

# Machine-readable marker prepended to TTS / spoken output (Node 06).
DISCLAIMER_TTS_EN = (
    "Important: This information is generated by the AuraMed AI assistant for "
    "decision support only. A licensed physician must review it before any "
    "clinical action."
)
DISCLAIMER_TTS_BN = (
    "গুরুত্বপূর্ণ: এই তথ্য AuraMed এআই সহকারী থেকে দেওয়া হচ্ছে এবং এটি শুধুমাত্র "
    "সিদ্ধান্ত-সহায়তার জন্য। কোনো চিকিৎসা ব্যবস্থার আগে একজন নিবন্ধিত চিকিৎসকের "
    "পর্যালোচনা আবশ্যক।"
)


def get_disclaimer(language: str = "en") -> str:
    """Return the mandatory disclaimer in the requested language."""
    return DISCLAIMER_BN if language.lower().startswith("bn") else DISCLAIMER_EN


def get_spoken_disclaimer(language: str = "en") -> str:
    """Disclaimer phrased for text-to-speech read-aloud (Node 06)."""
    return DISCLAIMER_TTS_BN if language.lower().startswith("bn") else DISCLAIMER_TTS_EN
